version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:3000"
    env_file:
      - .env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
